version: "3.9"
services:

  nginx_server: 
    container_name: nginx_web_server
    image: nginx:latest 
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8000:8000"
    networks:
      - project_network
    depends_on:
      - application 
  
  application:
    container_name: ml_application 
    build: ./
    env_file: ./environment.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/healthcheck/"]
      retries: 5
      interval: 10s
      timeout: 5s

    depends_on:
      - postgresql
      
    networks:
      - project_network

  postgresql:
    container_name: database 
    image: postgresql:latest 
    env_file: ./postgresql/postgresql.env
    ports:
      - "8080:8080"
    heatlhcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgresql_database"]
      retries: 5 
      interval: 10s
      timeout: 5s
    networks:
      - project_network

networks:
  project_network:
    external: True 
    name: "ml-network"
