version: "3.9"
services:
  
  application:
    container_name: ml_application 
    build: ./
    env_file: ./environment.env
    ports:
      - "8081:8081"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8081/healthcheck/"]
      retries: 5
      interval: 10s
      timeout: 5s
    networks:
      - project_network

networks:
  project_network:
    external: True 
    name: "ml-network"
