version: "3.9"
services:
  
  application:
    container_name: ml_application 
    build: ./
    env_file: ./environment.env
    ports:
      - "8080:8080"
    networks:
      - project_network

networks:
  project_network:
    external: True 
    name: "ml-network"
