version: "3.9"
services:

  nginx_server: 
    container_name: nginx_web_server
    image: nginx:latest 
    volumes: 
      - ../nginx/nginx.conf:/etc/nginx/nginx.conf 
    ports:
      - "8000:80"
    networks:
      - project_network
    depends_on:
      - application 
  
  application:
    container_name: ml_application 
    image: crazycoderrr/credit_card_application:latest
    env_file: 
      - ../env/proj.env
      - ../env/database.env
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/healthcheck/"]
      retries: 5
      interval: 10s
      timeout: 5s

    depends_on:
      - postgresql
      - pgadmin
      
    networks:
      - project_network

  postgresql:
    container_name: database 
    image: postgres:latest 
    env_file: ../env/database.env
    ports:
      - "5436:5436"
    command:
      - -p 5436
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    networks:
      - project_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: raj@nola.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    networks:
      - project_network

networks:
  project_network:
    external: True 
    name: "ml-network"

volumes:
  data:
    driver: local 
  pgadmin-data: 
    driver: local
    