APPLICATION_TABLE_FIELDS = (
    "ID",
    "CODE_GENDER",
    "FLAG_OWN_CAR",
    "FLAG_OWN_REALTY",
    "CNT_CHILDREN",
    "AMT_INCOME_TOTAL",
    "NAME_INCOME_TYPE",
    "NAME_EDUCATION_TYPE",
    "NAME_FAMILY_STATUS",
    "NAME_HOUSING_TYPE",
    "DAYS_BIRTH",
    "FLAG_MOBIL",
    "FLAG_PHONE",
    "FLAG_WORK_PHONE",
    "FLAG_EMAIL",
    "CNT_FAM_MEMBERS",
    "OCCUPATION_TYPE",
    'DAYS_EMPLOYED',
)

TRANSACTION_TABLE_FIELDS = (
    "ID",
    "STATUS",
    "MONTHS_BALANCE"
)