apiVersion: v1
kind: Service 
metadata:
  name: ml-application-service 
  namespace: ml-namespace 
spec:
  selector:
    app: ml-app
  ports:
    - name: http
      port: 7000
      targetPort: 8080
      protocol: TCP
      
---

apiVersion: v1
kind: Deployment 
metadata:
  name: application-deployment 
  namespace: app-namespace 
spec:
  selector:
    matchLabels:
      app: application-service 
  template:
    metadata:
      labels:
        app: application-service 
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: application-container 
          image: crazycoderrr/credit_card_application:latest
          ports:
            - containerPort: 8001
              protocol: TCP 
          envFrom:
            - configMapRef:
                - name: ml-application-map
          imagePullPolicy: IfNotPresent 