apiVersion: v1
kind: Service
metadata:
  name: ml-database-service
  namespace: ml-namespace 
spec:
  selector:
    labels:
      app: ml-db
  ports:
    - name: http 
      containerPort: 5432
      targetPort: 5432
      protocol: TCP 

---

apiVersion: v1
kind: StatefulSet
metadata:
  name: ml-database
  namespace: ml-namespace
spec:
  selector:
    matchLabels:
      app: ml-db 
  templates:
    metadata:
      labels: ml-db
    spec:
      containers:
        - name: database
          image: postgres:latest 
          ports:
            - containerPort: 5432 
              protocol: TCP
              targetPort: 5432
          imagePullPolicy: IfNotPresent 
          terminationGracePeriodSeconds: 60
          envFrom:
            secretRef:
              - name: ml-database-map