name: Credit Card Approval Project

on:
  pull_request:
    branches: [ "main" ]
    types:
      - 'closed'

permissions:
  contents: read

jobs:
  docker:
    env:
      DOCKER_IMAGE_TAG: crazycoderrr/credit_card_approval_application:latest
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
      - name: Buildling docker image 
        run: |
          cd deployment 
          docker-compose up -d 
      
      - name: Tagging docker image 
        run: |
          docket tag deployment_application ${{env.DOCKER_IMAGE_TAG}}

      - name: Pushing Docker image to the remote repository
        run: |
          docker push ${{env.DOCKER_IMAGE_TAG}}
          
          
          
