name: Email Notification Pipeline

on:
  pull_request:
    branches: [ "main" ]
    
  jobs:
    notification:
      runs-on: ubuntu-latest 
      
      steps:
        - name: Sending Email Notification 
          run: | 
            
      